//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/RendaActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/RendaActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @RendaActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @RendaActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""RendaActions"",
    ""maps"": [
        {
            ""name"": ""RendaMap"",
            ""id"": ""6986a6f6-3d69-4930-9a36-2003feed3b89"",
            ""actions"": [
                {
                    ""name"": ""RendaPress1"",
                    ""type"": ""Button"",
                    ""id"": ""1dabcc69-3238-4090-a263-13aea17afefb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RendaPress2"",
                    ""type"": ""Button"",
                    ""id"": ""9d0e67f6-f6e2-42a6-956e-d0fc0f581298"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug_StartRenda"",
                    ""type"": ""Button"",
                    ""id"": ""3cad9b2b-d348-40fa-b917-06e79bafbbcf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""123ae8cd-220d-4895-bf69-5b4870f118f7"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RendaPress1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f0d7be7-30f7-4478-a5e4-3568fbe2b319"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RendaPress2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a92948ed-8944-419b-be2b-d7bd350f3501"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug_StartRenda"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RendaMap
        m_RendaMap = asset.FindActionMap("RendaMap", throwIfNotFound: true);
        m_RendaMap_RendaPress1 = m_RendaMap.FindAction("RendaPress1", throwIfNotFound: true);
        m_RendaMap_RendaPress2 = m_RendaMap.FindAction("RendaPress2", throwIfNotFound: true);
        m_RendaMap_Debug_StartRenda = m_RendaMap.FindAction("Debug_StartRenda", throwIfNotFound: true);
    }

    ~@RendaActions()
    {
        UnityEngine.Debug.Assert(!m_RendaMap.enabled, "This will cause a leak and performance issues, RendaActions.RendaMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RendaMap
    private readonly InputActionMap m_RendaMap;
    private List<IRendaMapActions> m_RendaMapActionsCallbackInterfaces = new List<IRendaMapActions>();
    private readonly InputAction m_RendaMap_RendaPress1;
    private readonly InputAction m_RendaMap_RendaPress2;
    private readonly InputAction m_RendaMap_Debug_StartRenda;
    /// <summary>
    /// Provides access to input actions defined in input action map "RendaMap".
    /// </summary>
    public struct RendaMapActions
    {
        private @RendaActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public RendaMapActions(@RendaActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "RendaMap/RendaPress1".
        /// </summary>
        public InputAction @RendaPress1 => m_Wrapper.m_RendaMap_RendaPress1;
        /// <summary>
        /// Provides access to the underlying input action "RendaMap/RendaPress2".
        /// </summary>
        public InputAction @RendaPress2 => m_Wrapper.m_RendaMap_RendaPress2;
        /// <summary>
        /// Provides access to the underlying input action "RendaMap/Debug_StartRenda".
        /// </summary>
        public InputAction @Debug_StartRenda => m_Wrapper.m_RendaMap_Debug_StartRenda;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_RendaMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="RendaMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(RendaMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="RendaMapActions" />
        public void AddCallbacks(IRendaMapActions instance)
        {
            if (instance == null || m_Wrapper.m_RendaMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RendaMapActionsCallbackInterfaces.Add(instance);
            @RendaPress1.started += instance.OnRendaPress1;
            @RendaPress1.performed += instance.OnRendaPress1;
            @RendaPress1.canceled += instance.OnRendaPress1;
            @RendaPress2.started += instance.OnRendaPress2;
            @RendaPress2.performed += instance.OnRendaPress2;
            @RendaPress2.canceled += instance.OnRendaPress2;
            @Debug_StartRenda.started += instance.OnDebug_StartRenda;
            @Debug_StartRenda.performed += instance.OnDebug_StartRenda;
            @Debug_StartRenda.canceled += instance.OnDebug_StartRenda;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="RendaMapActions" />
        private void UnregisterCallbacks(IRendaMapActions instance)
        {
            @RendaPress1.started -= instance.OnRendaPress1;
            @RendaPress1.performed -= instance.OnRendaPress1;
            @RendaPress1.canceled -= instance.OnRendaPress1;
            @RendaPress2.started -= instance.OnRendaPress2;
            @RendaPress2.performed -= instance.OnRendaPress2;
            @RendaPress2.canceled -= instance.OnRendaPress2;
            @Debug_StartRenda.started -= instance.OnDebug_StartRenda;
            @Debug_StartRenda.performed -= instance.OnDebug_StartRenda;
            @Debug_StartRenda.canceled -= instance.OnDebug_StartRenda;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="RendaMapActions.UnregisterCallbacks(IRendaMapActions)" />.
        /// </summary>
        /// <seealso cref="RendaMapActions.UnregisterCallbacks(IRendaMapActions)" />
        public void RemoveCallbacks(IRendaMapActions instance)
        {
            if (m_Wrapper.m_RendaMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="RendaMapActions.AddCallbacks(IRendaMapActions)" />
        /// <seealso cref="RendaMapActions.RemoveCallbacks(IRendaMapActions)" />
        /// <seealso cref="RendaMapActions.UnregisterCallbacks(IRendaMapActions)" />
        public void SetCallbacks(IRendaMapActions instance)
        {
            foreach (var item in m_Wrapper.m_RendaMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RendaMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="RendaMapActions" /> instance referencing this action map.
    /// </summary>
    public RendaMapActions @RendaMap => new RendaMapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "RendaMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="RendaMapActions.AddCallbacks(IRendaMapActions)" />
    /// <seealso cref="RendaMapActions.RemoveCallbacks(IRendaMapActions)" />
    public interface IRendaMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "RendaPress1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRendaPress1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RendaPress2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRendaPress2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Debug_StartRenda" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDebug_StartRenda(InputAction.CallbackContext context);
    }
}
